-- Using DBeaver, set up a Bronze schema in your Postgres instance and create the necessary raw tables to store the initial data.

create schema if not exists bronze;

CREATE TABLE bronze.census_g01_nsw_lga_2016 (
	LGA_CODE_2016 varchar(50),
	Tot_P_M int,
	Tot_P_F int,
	Tot_P_P int,
	Age_0_4_yr_M int,
	Age_0_4_yr_F int,
	Age_0_4_yr_P int,
	Age_5_14_yr_M int,
	Age_5_14_yr_F int,
	Age_5_14_yr_P int,
	Age_15_19_yr_M int,
	Age_15_19_yr_F int,
	Age_15_19_yr_P int,
	Age_20_24_yr_M int,
	Age_20_24_yr_F int,
	Age_20_24_yr_P int,
	Age_25_34_yr_M int,
	Age_25_34_yr_F int,
	Age_25_34_yr_P int,
	Age_35_44_yr_M int,
	Age_35_44_yr_F int,
	Age_35_44_yr_P int,
	Age_45_54_yr_M int,
	Age_45_54_yr_F int,
	Age_45_54_yr_P int,
	Age_55_64_yr_M int,
	Age_55_64_yr_F int,
	Age_55_64_yr_P int,
	Age_65_74_yr_M int,
	Age_65_74_yr_F int,
	Age_65_74_yr_P int,
	Age_75_84_yr_M int,
	Age_75_84_yr_F int,
	Age_75_84_yr_P int,
	Age_85ov_M int,
	Age_85ov_F int,
	Age_85ov_P int,
	Counted_Census_Night_home_M int,
	Counted_Census_Night_home_F int,
	Counted_Census_Night_home_P int,
	Count_Census_Nt_Ewhere_Aust_M int,
	Count_Census_Nt_Ewhere_Aust_F int,
	Count_Census_Nt_Ewhere_Aust_P int,
	Indigenous_psns_Aboriginal_M int,
	Indigenous_psns_Aboriginal_F int,
	Indigenous_psns_Aboriginal_P int,
	Indig_psns_Torres_Strait_Is_M int,
	Indig_psns_Torres_Strait_Is_F int,
	Indig_psns_Torres_Strait_Is_P int,
	Indig_Bth_Abor_Torres_St_Is_M int,
	Indig_Bth_Abor_Torres_St_Is_F int,
	Indig_Bth_Abor_Torres_St_Is_P int,
	Indigenous_P_Tot_M int,
	Indigenous_P_Tot_F int,
	Indigenous_P_Tot_P int,
	Birthplace_Australia_M int,
	Birthplace_Australia_F int,
	Birthplace_Australia_P int,
	Birthplace_Elsewhere_M int,
	Birthplace_Elsewhere_F int,
	Birthplace_Elsewhere_P int,
	Lang_spoken_home_Eng_only_M int,
	Lang_spoken_home_Eng_only_F int,
	Lang_spoken_home_Eng_only_P int,
	Lang_spoken_home_Oth_Lang_M int,
	Lang_spoken_home_Oth_Lang_F int,
	Lang_spoken_home_Oth_Lang_P int,
	Australian_citizen_M int,
	Australian_citizen_F int,
	Australian_citizen_P int,
	Age_psns_att_educ_inst_0_4_M int,
	Age_psns_att_educ_inst_0_4_F int,
	Age_psns_att_educ_inst_0_4_P int,
	Age_psns_att_educ_inst_5_14_M int,
	Age_psns_att_educ_inst_5_14_F int,
	Age_psns_att_educ_inst_5_14_P int,
	Age_psns_att_edu_inst_15_19_M int,
	Age_psns_att_edu_inst_15_19_F int,
	Age_psns_att_edu_inst_15_19_P int,
	Age_psns_att_edu_inst_20_24_M int,
	Age_psns_att_edu_inst_20_24_F int,
	Age_psns_att_edu_inst_20_24_P int,
	Age_psns_att_edu_inst_25_ov_M int,
	Age_psns_att_edu_inst_25_ov_F int,
	Age_psns_att_edu_inst_25_ov_P int,
	High_yr_schl_comp_Yr_12_eq_M int,
	High_yr_schl_comp_Yr_12_eq_F int,
	High_yr_schl_comp_Yr_12_eq_P int,
	High_yr_schl_comp_Yr_11_eq_M int,
	High_yr_schl_comp_Yr_11_eq_F int,
	High_yr_schl_comp_Yr_11_eq_P int,
	High_yr_schl_comp_Yr_10_eq_M int,
	High_yr_schl_comp_Yr_10_eq_F int,
	High_yr_schl_comp_Yr_10_eq_P int,
	High_yr_schl_comp_Yr_9_eq_M int,
	High_yr_schl_comp_Yr_9_eq_F int,
	High_yr_schl_comp_Yr_9_eq_P int,
	High_yr_schl_comp_Yr_8_belw_M int,
	High_yr_schl_comp_Yr_8_belw_F int,
	High_yr_schl_comp_Yr_8_belw_P int,
	High_yr_schl_comp_D_n_g_sch_M int,
	High_yr_schl_comp_D_n_g_sch_F int,
	High_yr_schl_comp_D_n_g_sch_P int,
	Count_psns_occ_priv_dwgs_M int,
	Count_psns_occ_priv_dwgs_F int,
	Count_Persons_other_dwgs_F int,
	Count_psns_occ_priv_dwgs_P int,
	Count_Persons_other_dwgs_M int,
	Count_Persons_other_dwgs_P int
);


CREATE TABLE airbnb (
	LISTING_ID INT,
	SCRAPE_ID BIGINT,
	SCRAPED_DATE DATE,
	HOST_ID INT,
	HOST_NAME VARCHAR(50),
	HOST_SINCE DATE,
	HOST_IS_SUPERHOST BOOLEAN,
	HOST_NEIGHBOURHOOD VARCHAR(50),
	LISTING_NEIGHBOURHOOD VARCHAR(50),
	PROPERTY_TYPE VARCHAR(50),
	ROOM_TYPE VARCHAR(50),
	ACCOMMODATES INT,
	PRICE INT,
	HAS_AVAILABILITY BOOLEAN,
	AVAILABILITY_30 INT,
	NUMBER_OF_REVIEWS INT,
	REVIEW_SCORES_RATING INT,
	REVIEW_SCORES_ACCURACY INT,
	REVIEW_SCORES_CLEANLINESS INT,
	REVIEW_SCORES_CHECKIN INT,
	REVIEW_SCORES_COMMUNICATION INT,
	REVIEW_SCORES_VALUE INT
);

create table census_g02_nsw_lga_2016(
	LGA_CODE_2016 VARCHAR(50),
	MEDIAN_AGE_PERSONS INT,
	MEDIAN_MORTGAGE_REPAY_MONTHLY INT,
	MEDIAN_TOT_PRSNL_INC_WEEKLY INT,
	MEDIAN_RENT_WEEKLY INT, 
	MEDIAN_TOT_FAM_INC_WEEKLY INT,
	AVERAGE_NUM_PSNS_PER_BEDROOM real,
	MEDIAN_TOT_HHD_INC_WEEKLY INT,
	AVERAGE_HOUSEHOLD_SIZE real
);

create table nsw_lga_code(
	LGA_CODE INT,
	LGA_NAME VARCHAR(50)
);

create table nsw_lga_suburb(
	LGA_NAME VARCHAR(50),
	SUBURB_NAME VARCHAR(50)
);

