snapshots:
  - name: snap_listings
    description: "Tracks changes to Airbnb listing data over time using a timestamp-based snapshot strategy SCD(2)."
    target_schema: snapshots
    unique_key: listing_id
    strategy: timestamp
    updated_at: scraped_date

    columns:
      - name: listing_id
        description: Identifier for each listing.
        tests:
          - not_null
      - name: host_id
        description: Unique identifier for the host of the listing.
      - name: scrape_id
        description: Identifier for the scraping session used to collect the data.
      - name: scraped_date
        description: Timestamp when the listing data was scraped (used for change tracking).
      - name: listing_neighbourhood
        description: The general area or Local Government Area (LGA) where the listing is located.
      - name: property_type
        description: Type of property listed, e.g., Apartment, House, Townhouse.
      - name: room_type
        description: Type of room available, e.g., Entire home/apt, Private room, Shared room.
      - name: accommodates
        description: The maximum number of guests the listing can accommodate.
      - name: price
        description: The nightly price of the listing.
      - name: has_availability
        description: Indicates whether the listing is currently available for booking (TRUE/FALSE).
      - name: availability_30
        description: Number of days the listing is available in the next 30 days.
      - name: dbt_scd_id
        description: "Surrogate ID generated by dbt to track different versions of the same LGA record."
      - name: dbt_updated_at
        description: "Timestamp when the snapshot detected a change in the LGA record."
      - name: dbt_valid_from
        description: "Timestamp indicating when the current version of the LGA record became valid."
      - name: dbt_valid_to
        description: "Timestamp indicating when the current version was superseded. NULL means the record is current."

  - name: snap_hosts
    description: >
      Snapshot of host dimension with SCD Type 2 logic to capture changes in host attributes like name, neighbourhood, and superhost status over time.
    target_schema: snapshots
    unique_key: host_id
    strategy: timestamp
    updated_at: scraped_date

    columns:
      - name: host_id
        description: Unique identifier for the host.
        tests:
          - not_null
      - name: host_name
        description: Name of the host.
      - name: host_neighbourhood
        description: Neighbourhood of the host, if available.
      - name: host_since
        description: The date the host first registered on Airbnb.
      - name: host_is_superhost
        description: Whether the host is a superhost.
      - name: scraped_date
        description: The date on which the host data was scraped.
      - name: dbt_scd_id
        description: "Surrogate ID generated by dbt to track different versions of the same LGA record."
      - name: dbt_updated_at
        description: "Timestamp when the snapshot detected a change in the LGA record."
      - name: dbt_valid_from
        description: "Timestamp indicating when the current version of the LGA record became valid."
      - name: dbt_valid_to
        description: "Timestamp indicating when the current version was superseded. NULL means the record is current."

  - name: snap_lga
    description: "Tracks changes to Local Government Area (LGA) data over time using a check-based snapshot strategy (SCD Type 2)."
    target_schema: snapshots
    unique_key: lga_code
    strategy: check
    check_cols: ["lga_name"]

    columns:
      - name: lga_code
        description: "Unique code identifying each Local Government Area (LGA)."
        tests:
          - not_null
          - unique
      - name: lga_name
        description: "Name of the Local Government Area."
      - name: dbt_scd_id
        description: "Surrogate ID generated by dbt to track different versions of the same LGA record."
      - name: dbt_updated_at
        description: "Timestamp when the snapshot detected a change in the LGA record."
      - name: dbt_valid_from
        description: "Timestamp indicating when the current version of the LGA record became valid."
      - name: dbt_valid_to
        description: "Timestamp indicating when the current version was superseded. NULL means the record is current."

  - name: snap_suburb
    description: "Tracks changes to suburb and LGA mappings over time using a check-based snapshot strategy (SCD Type 2)."
    target_schema: snapshots
    unique_key: surrogate_key
    strategy: check
    check_cols: ["suburb_name"]

    columns:
      - name: surrogate_key
        description: "Surrogate key generated from LGA name and suburb name combination."
        tests:
          - not_null
          - unique
      - name: lga_name
        description: "Name of the Local Government Area (LGA)."
      - name: suburb_name
        description: "Name of the suburb."
      - name: dbt_scd_id
        description: "Surrogate ID generated by dbt to track different versions of the same suburb record."
      - name: dbt_updated_at
        description: "Timestamp when the snapshot detected a change in the suburb record."
      - name: dbt_valid_from
        description: "Timestamp indicating when the current version of the suburb record became valid."
      - name: dbt_valid_to
        description: "Timestamp indicating when the current version was superseded. NULL means the record is current."
