version: 2

sources:
  - name: bronze
    database: postgres
    schema: bronze
    tables:
      - name: airbnb_05_2020
      - name: census_g01_nsw_lga_2016
      - name: census_g02_nsw_lga_2016
      - name: nsw_lga_code
      - name: nsw_lga_suburb
